# Settings for the MySQL subchart
mysql:
  auth:
    database: devops_db
    username: devops_user
    password: devops_password
    rootPassword: root_password
  primary:
    persistence:
      enabled: false # Set to true for production/real labs

# Your Application settings
image:
  repository: devops-app
  tag: latest
  pullPolicy: IfNotPresent