replicaCount: 1

image:
  repository: devops-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

mysql:
  auth:
    database: devops_db
    username: devops_user
    password: devops_password
    rootPassword: root_password