apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-app-chart.fullname" . }}-db-secret
type: Opaque
data:
  # Values must be base64 encoded. 
  # Example: 'root' in base64 is 'cm9vdA=='
  db-username: {{ .Values.mongodb.auth.username | default "root" | b64enc | quote }}
  db-password: {{ .Values.mongodb.auth.password | default "password123" | b64enc | quote }}