name: DevOps Pipeline

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This new step creates a lowercase version of the repo name and the branch tag
      - name: Prepare Image Metadata
        id: meta
        run: |
          # Convert Repo Name to lowercase
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT
          
          # Create the dynamic tag (e.g., dev-a1b2c3d)
          BRANCH=${GITHUB_REF#refs/heads/}
          SHA=$(git rev-parse --short HEAD)
          echo "tag=${BRANCH}-${SHA}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.branch }}-latest

      - name: Provision local cluster with vind
        run: |
          echo "Downloading vCluster CLI..."
            curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64"
            sudo install -c -m 0755 vcluster /usr/local/bin
            rm -f vcluster
          
            echo "Setting driver to Docker (vind mode)..."
            vcluster use driver docker
          
            echo "Creating the Kubernetes cluster..."
            vcluster create ci-cluster
          
            echo "Verifying cluster is running..."
            kubectl cluster-info
            kubectl get nodes